-- SignTalk schema for SQLite - the fallback backend/db.py uses when there is
-- no PostgreSQL to talk to. Applied automatically on first connection, so it
-- must stay idempotent: everything here is CREATE ... IF NOT EXISTS.
--
-- Kept table-for-table and column-for-column with db/schema.sql so the SQL in
-- backend/library.py and backend/auth/sql_store.py runs against either. The
-- differences are all type-level:
--
--   UUID          -> TEXT, generated by the default expression below
--   TIMESTAMPTZ   -> TEXT holding an ISO-8601 UTC timestamp (sorts correctly)
--   BYTEA         -> BLOB
--   BOOLEAN       -> INTEGER 0/1
--   TEXT[]        -> TEXT_ARRAY holding a JSON array
--   JSONB / INET  -> TEXT
--   CITEXT        -> TEXT COLLATE NOCASE
--
-- now() and gen_random_uuid() are Python functions registered on the
-- connection by backend/db.py. Regex CHECKs are dropped: SQLite has no regex
-- operator, and the service layer validates the same shapes before a write.
-- See docs/schema.md for the reasoning behind each table.


CREATE TABLE IF NOT EXISTS schema_migrations (
    version     INTEGER     PRIMARY KEY,
    name        TEXT        NOT NULL,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT (now())
);


-- ===========================================================================
-- 1. IDENTITY
-- ===========================================================================

CREATE TABLE IF NOT EXISTS users (
    id                  TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    email               TEXT        NOT NULL UNIQUE COLLATE NOCASE,
    username            TEXT        NOT NULL UNIQUE COLLATE NOCASE,
    phone               TEXT        UNIQUE,
    password_hash       TEXT        NOT NULL,

    email_verified_at   TIMESTAMPTZ,
    phone_verified_at   TIMESTAMPTZ,

    failed_attempts     INTEGER     NOT NULL DEFAULT 0,
    locked_until        TIMESTAMPTZ,

    last_login_at       TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT (now()),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT (now()),
    deleted_at          TIMESTAMPTZ,

    CONSTRAINT users_attempts_sane CHECK (failed_attempts >= 0)
);

CREATE TRIGGER IF NOT EXISTS users_touch AFTER UPDATE ON users
FOR EACH ROW WHEN NEW.updated_at IS OLD.updated_at
BEGIN
    UPDATE users SET updated_at = now() WHERE id = NEW.id;
END;

CREATE INDEX IF NOT EXISTS users_active_idx ON users (created_at DESC)
    WHERE deleted_at IS NULL;


-- ===========================================================================
-- 2. AUTHENTICATION
-- ===========================================================================

CREATE TABLE IF NOT EXISTS sessions (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    user_id         TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      BLOB        NOT NULL UNIQUE,
    method          TEXT        NOT NULL,

    issued_at       TIMESTAMPTZ NOT NULL DEFAULT (now()),
    expires_at      TIMESTAMPTZ NOT NULL,
    last_seen_at    TIMESTAMPTZ,
    revoked_at      TIMESTAMPTZ,

    ip              TEXT,
    user_agent      TEXT,

    CONSTRAINT sessions_method    CHECK (method IN ('password', 'recovery_code')),
    CONSTRAINT sessions_token_len CHECK (length(token_hash) = 32)
);

CREATE INDEX IF NOT EXISTS sessions_live_idx ON sessions (user_id)
    WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions (expires_at);


CREATE TABLE IF NOT EXISTS otp_challenges (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    user_id         TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    challenge_ref   BLOB        NOT NULL UNIQUE,

    channel         TEXT        NOT NULL,
    destination     TEXT        NOT NULL,
    code_hash       BLOB        NOT NULL,
    salt            BLOB        NOT NULL,

    attempts_left   INTEGER     NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,
    consumed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT otp_channel  CHECK (channel IN ('email', 'sms')),
    CONSTRAINT otp_attempts CHECK (attempts_left >= 0),
    CONSTRAINT otp_ref_len  CHECK (length(challenge_ref) = 32)
);

CREATE INDEX IF NOT EXISTS otp_user_idx ON otp_challenges (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS otp_expiry_idx ON otp_challenges (expires_at);


CREATE TABLE IF NOT EXISTS recovery_tickets (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    user_id         TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ticket_ref      BLOB        NOT NULL UNIQUE,
    channel         TEXT        NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,
    consumed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT ticket_channel CHECK (channel IN ('email', 'sms')),
    CONSTRAINT ticket_ref_len CHECK (length(ticket_ref) = 32)
);

CREATE INDEX IF NOT EXISTS ticket_user_idx ON recovery_tickets (user_id);
CREATE INDEX IF NOT EXISTS ticket_expiry_idx ON recovery_tickets (expires_at);


CREATE TABLE IF NOT EXISTS auth_events (
    id          INTEGER     PRIMARY KEY AUTOINCREMENT,
    user_id     TEXT        REFERENCES users(id) ON DELETE SET NULL,
    event       TEXT        NOT NULL,
    channel     TEXT,
    ip          TEXT,
    user_agent  TEXT,
    detail      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS auth_events_user_idx ON auth_events (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS auth_events_type_idx ON auth_events (event, created_at DESC);


-- ===========================================================================
-- 3. SIGN LIBRARY
-- ===========================================================================

CREATE TABLE IF NOT EXISTS languages (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    owner_id        TEXT        REFERENCES users(id) ON DELETE CASCADE,
    name            TEXT        NOT NULL,
    description     TEXT,
    source          TEXT        NOT NULL DEFAULT 'user',

    visibility      TEXT        NOT NULL DEFAULT 'private',
    published_at    TIMESTAMPTZ,
    forked_from_id  TEXT        REFERENCES languages(id) ON DELETE SET NULL,

    hand_control    TEXT        NOT NULL DEFAULT 'both',
    sample_target   INTEGER     NOT NULL DEFAULT 40,

    -- Migration 3. Also listed in backend/db.py COLUMN_MIGRATIONS so a database
    -- created before them gains the columns on next open.
    gesture_translation BOOLEAN NOT NULL DEFAULT 0,
    gesture_interval_ms INTEGER NOT NULL DEFAULT 1200,
    -- Migration 4: the spoken language the symbols spell out (BCP-47 code).
    spoken_language TEXT NOT NULL DEFAULT 'en',
    -- Migration 5: what kind of sign language this is, in the owner's words.
    tag             TEXT NOT NULL DEFAULT '',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT languages_name_len     CHECK (length(name) BETWEEN 1 AND 80),
    CONSTRAINT languages_source       CHECK (source IN ('user', 'asl_dataset', 'imported')),
    CONSTRAINT languages_visibility   CHECK (visibility IN ('private', 'unlisted', 'public')),
    CONSTRAINT languages_published    CHECK (visibility = 'private' OR published_at IS NOT NULL),
    CONSTRAINT languages_no_self_fork CHECK (forked_from_id IS NOT id),
    CONSTRAINT languages_hand_control CHECK (hand_control IN ('left', 'right', 'both')),
    CONSTRAINT languages_sample_target CHECK (sample_target BETWEEN 5 AND 500)
);

CREATE UNIQUE INDEX IF NOT EXISTS languages_owner_name_idx
    ON languages (owner_id, lower(name)) WHERE owner_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS languages_builtin_name_idx
    ON languages (lower(name)) WHERE owner_id IS NULL;
CREATE INDEX IF NOT EXISTS languages_public_idx
    ON languages (published_at DESC) WHERE visibility = 'public';

CREATE TRIGGER IF NOT EXISTS languages_touch AFTER UPDATE ON languages
FOR EACH ROW WHEN NEW.updated_at IS OLD.updated_at
BEGIN
    UPDATE languages SET updated_at = now() WHERE id = NEW.id;
END;


CREATE TABLE IF NOT EXISTS signs (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    language_id     TEXT        NOT NULL REFERENCES languages(id) ON DELETE CASCADE,
    name            TEXT        NOT NULL,
    has_phrases     BOOLEAN     NOT NULL DEFAULT 0,
    phrases         TEXT_ARRAY  NOT NULL DEFAULT '[]',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT signs_name_len CHECK (length(name) BETWEEN 1 AND 80),
    CONSTRAINT signs_phrases_agree CHECK (has_phrases OR json_array_length(phrases) = 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS signs_language_name_idx
    ON signs (language_id, lower(name));

CREATE TRIGGER IF NOT EXISTS signs_touch AFTER UPDATE ON signs
FOR EACH ROW WHEN NEW.updated_at IS OLD.updated_at
BEGIN
    UPDATE signs SET updated_at = now() WHERE id = NEW.id;
END;


CREATE TABLE IF NOT EXISTS symbols (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    sign_id         TEXT        NOT NULL REFERENCES signs(id) ON DELETE CASCADE,
    name            TEXT        NOT NULL,
    output_kind     TEXT        NOT NULL DEFAULT 'text',
    output_value    TEXT        NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT symbols_name_len     CHECK (length(name) BETWEEN 1 AND 80),
    CONSTRAINT symbols_output_kind  CHECK (output_kind IN ('text', 'space', 'key', 'combo')),
    CONSTRAINT symbols_output_value CHECK (output_kind IN ('text', 'space') OR length(output_value) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS symbols_sign_name_idx
    ON symbols (sign_id, lower(name));

CREATE TRIGGER IF NOT EXISTS symbols_touch AFTER UPDATE ON symbols
FOR EACH ROW WHEN NEW.updated_at IS OLD.updated_at
BEGIN
    UPDATE symbols SET updated_at = now() WHERE id = NEW.id;
END;


CREATE TABLE IF NOT EXISTS symbol_views (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    symbol_id       TEXT        NOT NULL REFERENCES symbols(id) ON DELETE CASCADE,
    view            TEXT        NOT NULL,

    sample_count    INTEGER     NOT NULL,
    -- float32, little-endian, row-major (sample_count, 126). Source of truth.
    landmarks       BLOB        NOT NULL,
    -- Derived cache, safe to drop and rebuild.
    features        BLOB,
    feature_version INTEGER,

    quality_spread  REAL,
    captured_at     TIMESTAMPTZ NOT NULL DEFAULT (now()),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT views_view_len   CHECK (length(view) BETWEEN 1 AND 40),
    CONSTRAINT views_count      CHECK (sample_count > 0),
    CONSTRAINT views_blob_size  CHECK (length(landmarks) = sample_count * 126 * 4),
    CONSTRAINT views_cache_pair CHECK ((features IS NULL) = (feature_version IS NULL))
);

-- The upsert in library.store_samples targets exactly this index.
CREATE UNIQUE INDEX IF NOT EXISTS symbol_views_symbol_view_idx
    ON symbol_views (symbol_id, lower(view));
CREATE INDEX IF NOT EXISTS symbol_views_symbol_idx ON symbol_views (symbol_id);
CREATE INDEX IF NOT EXISTS symbol_views_stale_idx ON symbol_views (feature_version);

CREATE TRIGGER IF NOT EXISTS symbol_views_touch AFTER UPDATE ON symbol_views
FOR EACH ROW WHEN NEW.updated_at IS OLD.updated_at
BEGIN
    UPDATE symbol_views SET updated_at = now() WHERE id = NEW.id;
END;


-- One reference picture per symbol, for sign-to-sign translation. Opt-in per
-- language (gesture_translation) and thumbnail-sized - see db/schema.sql.
CREATE TABLE IF NOT EXISTS symbol_images (
    symbol_id       TEXT        PRIMARY KEY REFERENCES symbols(id) ON DELETE CASCADE,
    mime            TEXT        NOT NULL,
    image           BLOB        NOT NULL,
    width           INTEGER,
    height          INTEGER,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT symbol_images_mime CHECK (mime IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT symbol_images_size CHECK (length(image) BETWEEN 1 AND 400000)
);


-- ===========================================================================
-- 4. SHARING
-- ===========================================================================

CREATE TABLE IF NOT EXISTS language_installs (
    user_id         TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    language_id     TEXT        NOT NULL REFERENCES languages(id) ON DELETE CASCADE,
    installed_at    TIMESTAMPTZ NOT NULL DEFAULT (now()),
    PRIMARY KEY (user_id, language_id)
);

CREATE INDEX IF NOT EXISTS installs_language_idx ON language_installs (language_id);


CREATE TABLE IF NOT EXISTS language_reports (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    language_id     TEXT        NOT NULL REFERENCES languages(id) ON DELETE CASCADE,
    reporter_id     TEXT        REFERENCES users(id) ON DELETE SET NULL,
    reason          TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),
    resolved_at     TIMESTAMPTZ,

    CONSTRAINT reports_reason_len CHECK (length(reason) BETWEEN 1 AND 2000)
);

CREATE INDEX IF NOT EXISTS reports_open_idx ON language_reports (created_at DESC)
    WHERE resolved_at IS NULL;


-- ===========================================================================
-- 5. USAGE
-- ===========================================================================

CREATE TABLE IF NOT EXISTS interpretation_sessions (
    id              TEXT        PRIMARY KEY DEFAULT (lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))),
    user_id         TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    language_id     TEXT        REFERENCES languages(id) ON DELETE SET NULL,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),
    ended_at        TIMESTAMPTZ,

    CONSTRAINT interp_window CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE INDEX IF NOT EXISTS interp_user_idx
    ON interpretation_sessions (user_id, started_at DESC);


CREATE TABLE IF NOT EXISTS interpretation_readings (
    id              INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id      TEXT        NOT NULL REFERENCES interpretation_sessions(id) ON DELETE CASCADE,
    symbol_id       TEXT        REFERENCES symbols(id) ON DELETE SET NULL,
    label           TEXT        NOT NULL,
    confidence      REAL        NOT NULL,
    matched_view    TEXT,
    recognised_at   TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT readings_confidence CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE INDEX IF NOT EXISTS readings_session_idx
    ON interpretation_readings (session_id, recognised_at);


CREATE TABLE IF NOT EXISTS user_preferences (
    user_id         TEXT        PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    theme           TEXT,
    camera_index    INTEGER     NOT NULL DEFAULT 0,
    mirror_preview  BOOLEAN     NOT NULL DEFAULT 1,
    min_confidence  REAL        NOT NULL DEFAULT 0.55,
    -- Migration 6. Also in backend/db.py COLUMN_MIGRATIONS, so a database made
    -- before them gains the columns on next open.
    camera_device_id   TEXT        NOT NULL DEFAULT '',
    show_skeleton      BOOLEAN     NOT NULL DEFAULT 1,
    pace               TEXT        NOT NULL DEFAULT 'careful',
    capture_countdown  INTEGER     NOT NULL DEFAULT 3,
    reduce_motion      BOOLEAN     NOT NULL DEFAULT 0,
    overlay_x          REAL        NOT NULL DEFAULT 0.68,
    overlay_y          REAL        NOT NULL DEFAULT 0.06,
    overlay_width      REAL        NOT NULL DEFAULT 0.26,
    overlay_opacity    REAL        NOT NULL DEFAULT 0.95,
    overlay_caption    BOOLEAN     NOT NULL DEFAULT 1,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT (now()),

    CONSTRAINT prefs_camera     CHECK (camera_index >= 0),
    CONSTRAINT prefs_confidence CHECK (min_confidence >= 0 AND min_confidence <= 1)
);

CREATE TRIGGER IF NOT EXISTS user_preferences_touch AFTER UPDATE ON user_preferences
FOR EACH ROW WHEN NEW.updated_at IS OLD.updated_at
BEGIN
    UPDATE user_preferences SET updated_at = now() WHERE user_id = NEW.user_id;
END;


INSERT OR IGNORE INTO schema_migrations (version, name) VALUES (1, 'initial schema');
INSERT OR IGNORE INTO schema_migrations (version, name) VALUES (2, 'trainer configuration and symbol output');
INSERT OR IGNORE INTO schema_migrations (version, name) VALUES (3, 'gesture translation and symbol images');
INSERT OR IGNORE INTO schema_migrations (version, name) VALUES (4, 'spoken language');
INSERT OR IGNORE INTO schema_migrations (version, name) VALUES (5, 'language tag');
INSERT OR IGNORE INTO schema_migrations (version, name) VALUES (6, 'preferences people can change');

-- Backfill for languages made before tags existed. Idempotent: only blanks.
UPDATE languages SET tag = 'Indian Sign Language'   WHERE tag = '' AND upper(name) = 'ISL';
UPDATE languages SET tag = 'American Sign Language' WHERE tag = '' AND upper(name) = 'ASL';
UPDATE languages SET tag = 'Bengali Sign Language'  WHERE tag = '' AND upper(name) = 'BSL';
